; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:transmitter]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-samd
src_filter = +<transmitter/>
framework = arduino
lib_deps = 
	nrf24/RF24@^1.6.0
upload_port = COM3
monitor_port = COM3
monitor_speed = 9600

[env:receiver]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-samd
src_filter = +<receiver/>
framework = arduino
lib_deps = 
	nrf24/RF24@^1.6.0
upload_port = COM6
monitor_port = COM6
monitor_speed = 9600
